nameOverride:
fullnameOverride:

crds:
  install: true

rbac:
  create: true

controller:
  replicas: 1
  container:
    image:
      repository: europe-docker.pkg.dev/coremaker/eu.gcr.io/postgres-operator
      tag: v1.0.5
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi

    logging:
      log_level: info
      encoder: json
      stacktrace_level: panic

  # How often the controllers should reconcile
  # https://github.com/coremaker/postgres-operator/blob/eb06156200a5d8dedd819b55face46dcf2a629dc/main.go#L70
  timers:
    databaseReconciler: 300s
    userReconciler: 300s
    schemaReconciler: 300s
  
serviceAccount:
  create: true

sidecarContainers: []
